In [116]:
import pandas as pd
#load csv of edges 
allchampion_edges = pd.read_csv('datasets/csv/allchampions_edges_2.csv', sep=',', engine='python')
top_edges = pd.read_csc('datasets/csv/top_edges_2.csv', sep=',', engine='python')

In [117]:
allchampion_edges

           Source      Target    Weight
0          Ezreal      Lucian  0.504851
1          Ezreal       Vayne  0.474310
2          Lucian       Vayne  0.433064
3         Caitlyn      Ezreal  0.378187
4           Yasuo         Zed  0.344551
5          Ezreal       Sivir  0.338395
6      Blitzcrank      Thresh  0.320681
7         Alistar      Thresh  0.314113
8          Lucian       Sivir  0.311336
9         Caitlyn       Vayne  0.304238
10        Caitlyn      Lucian  0.298814
11           Nami      Soraka  0.293109
12        Morgana      Thresh  0.282001
13           Lulu        Nami  0.277865
14           Pyke      Thresh  0.268003
15        Alistar       Braum  0.265273
16         Irelia       Yasuo  0.260559
17        Caitlyn       Sivir  0.250721
18        Morgana      Soraka  0.241664
19        Morgana        Nami  0.241024
20           Lulu      Soraka  0.240323
21          Sivir       Vayne  0.239389
22         Ezreal        Jinx  0.237817
23         Ezreal      Thresh  0.234111
24        Caitlyn        Jinx  0.224639
25          Braum      Thresh  0.224526
26          Janna      Soraka  0.223565
27        Alistar     Morgana  0.222764
28           Ashe      Ezreal  0.222487
29        Alistar  Blitzcrank  0.221649
...           ...         ...       ...
7510       Syndra       Teemo  0.001327
7511  Mordekaiser      Veigar  0.001318
7512       Anivia       Taric  0.001316
7513       Illaoi      Syndra  0.001304
7514       Kennen     Warwick  0.001271
7515         Gnar     Nidalee  0.001264
7516     Volibear       Xayah  0.001262
7517      Karthus       Xayah  0.001240
7518         Azir      Rammus  0.001240
7519        Neeko     Warwick  0.001238
7520       Syndra      Yorick  0.001238
7521        Diana        Udyr  0.001226
7522      Camille  Tryndamere  0.001214
7523         Bard      Twitch  0.001141
7524        Ivern        Nami  0.001141
7525     Malzahar        Udyr  0.001132
7526        Braum  Tryndamere  0.001079
7527      Evelynn      Maokai  0.001039
7528       Rammus       Xayah  0.000998
7529         Azir       Garen  0.000993
7530        Janna        Udyr  0.000958
7531        Akali        Udyr  0.000934
7532         Udyr         Zoe  0.000923
7533         Udyr       Varus  0.000922
7534      Orianna        Udyr  0.000902
7535     Katarina     Sejuani  0.000880
7536     Katarina        Udyr  0.000707
7537    Lissandra        Udyr  0.000535
7538        Poppy        Udyr  0.000520
7539         Nami        Udyr  0.000416

[7540 rows x 3 columns]

In [34]:
import json

with open('datasets/csv/id_to_key' + '.json', encoding='utf-8') as g:
    id_to_key_data = json.load(g)

to_dict = {}
to_dict = id_to_key_data

In [61]:
def dict_to_df(d, col1, col2):
    result = pd.Series(d, name=col2)
    result.index.name = col1
    result = result.reset_index()
    return result

In [47]:
s = pd.Series(to_dict, name='Key')
s.index.name = 'Champion'
df = s.reset_index()
df

         Champion  Key
0          Aatrox  266
1            Ahri  103
2           Akali   84
3         Alistar   12
4           Amumu   32
5          Anivia   34
6           Annie    1
7            Ashe   22
8     AurelionSol  136
9            Azir  268
10           Bard  432
11     Blitzcrank   53
12          Brand   63
13          Braum  201
14        Caitlyn   51
15        Camille  164
16     Cassiopeia   69
17        Chogath   31
18          Corki   42
19         Darius  122
20          Diana  131
21         Draven  119
22        DrMundo   36
23           Ekko  245
24          Elise   60
25        Evelynn   28
26         Ezreal   81
27   Fiddlesticks    9
28          Fiora  114
29           Fizz  105
..            ...  ...
113         Taric   44
114         Teemo   17
115        Thresh  412
116      Tristana   18
117       Trundle   48
118    Tryndamere   23
119   TwistedFate    4
120        Twitch   29
121          Udyr   77
122         Urgot    6
123         Varus  110
124         Vayne   67
125        Veigar   45
126        Velkoz  161
127            Vi  254
128        Viktor  112
129      Vladimir    8
130      Volibear  106
131       Warwick   19
132         Xayah  498
133        Xerath  101
134       XinZhao    5
135         Yasuo  157
136        Yorick   83
137           Zac  154
138           Zed  238
139         Ziggs  115
140        Zilean   26
141           Zoe  142
142          Zyra  143

[143 rows x 2 columns]

In [118]:
def map_champ_id_to_key(champion_edges, id_key_tb):
    champion_edges['Source'] = champion_edges['Source'].map(id_key_tb.set_index('Champion')['Key']) 
    champion_edges['Target'] = champion_edges['Target'].map(id_key_tb.set_index('Champion')['Key']) 
    return champion_edges

In [119]:
allchampion_edges2 = allchampion_edges
champion_id_to_key = map_champ_id_to_key(allchampion_edges2, df)
champion_id_to_key

      Source  Target    Weight
0         81     236  0.504851
1         81      67  0.474310
2        236      67  0.433064
3         51      81  0.378187
4        157     238  0.344551
5         81      15  0.338395
6         53     412  0.320681
7         12     412  0.314113
8        236      15  0.311336
9         51      67  0.304238
10        51     236  0.298814
11       267      16  0.293109
12        25     412  0.282001
13       117     267  0.277865
14       555     412  0.268003
15        12     201  0.265273
16        39     157  0.260559
17        51      15  0.250721
18        25      16  0.241664
19        25     267  0.241024
20       117      16  0.240323
21        15      67  0.239389
22        81     222  0.237817
23        81     412  0.234111
24        51     222  0.224639
25       201     412  0.224526
26        40      16  0.223565
27        12      25  0.222764
28        22      81  0.222487
29        12      53  0.221649
...      ...     ...       ...
7510     134      17  0.001327
7511      82      45  0.001318
7512      34      44  0.001316
7513     420     134  0.001304
7514      85      19  0.001271
7515     150      76  0.001264
7516     106     498  0.001262
7517      30     498  0.001240
7518     268      33  0.001240
7519     518      19  0.001238
7520     134      83  0.001238
7521     131      77  0.001226
7522     164      23  0.001214
7523     432      29  0.001141
7524     427     267  0.001141
7525      90      77  0.001132
7526     201      23  0.001079
7527      28      57  0.001039
7528      33     498  0.000998
7529     268      86  0.000993
7530      40      77  0.000958
7531      84      77  0.000934
7532      77     142  0.000923
7533      77     110  0.000922
7534      61      77  0.000902
7535      55     113  0.000880
7536      55      77  0.000707
7537     127      77  0.000535
7538      78      77  0.000520
7539     267      77  0.000416

[7540 rows x 3 columns]

In [8]:
import json 

user_name = input("enter summoner: ")

with open('datasets/csv/user_vectors_tf_idf' + '.json', encoding='utf-8' ) as f:
    user_tfidf_data = json.load(f)
    
user_tfidf_data["Tuder"][11]

#try to get each user's champion ID and the tfidf value

0.4461922121888246

In [29]:
def get_indices_value(a):
    d = {}
    for i in range(len(a)):
        if a[i] > 0:
            d[i] = a[i]
    return d

In [30]:
def filter_user_tfidf(user_vector):
    to_original_filtered = get_indices_value(user_vector)
    return to_original_filtered

In [167]:
def get_recommendation(filtered_user_df, weight_edges):
    f = dict_to_df(filtered_user_df, 'Id', 'tfidf')
    filtered_edges = weight_edges[weight_edges['Source'].isin(f['Id'])].copy()
    filtered_edges = filtered_edges[~filtered_edges['Target'].isin(f['Id'])].copy()
    filtered_edges['Weight*Tfidf'] = filtered_edges.apply(lambda row: filtered_user_df.loc[filtered_user_df['Id'] == row['Source'].item(), 'tfidf'].item() * row['Weight'], axis=1)
    filtered_edges['sum_weighted_edges'] = filtered_edges.groupby(['Target'])['Weight*Tfidf'].transform(lambda x: x.sum())
    filtered_edges.sort_values(by='sum_weighted_edges', ascending=False, inplace=True)
    recommendation_lists_ids = filtered_edges[['Target','sum_weighted_edges']].copy()
    recommendation_lists_ids.drop_duplicates(subset='Target', inplace=True)
    return recommendation_lists_ids

In [168]:
def map_key_to_champ_id(recomm_lists_id, id_key_tb):
    result = recomm_lists_id.copy()
    result['Target'] = result['Target'].map(id_key_tb.set_index('Key')['Champion']) 
    return result

In [62]:
filtered = filter_user_tfidf(user_tfidf_data["Tuder"])

In [145]:
filtered_df = dict_to_df(filtered, 'Id', 'tfidf')
filtered_df.loc[filtered_df['Id'] == 141, 'tfidf'].item()

0.5324192202393978

In [177]:
filtered_df

     Id     tfidf
0    11  0.446192
1    77  0.791534
2    83  0.852532
3    87  0.826037
4   115  2.450499
5   135  1.274906
6   141  0.532419
7   154  0.396864
8   220  0.134096
9   226  0.535074
10  230  1.681920
11  258  1.302800
12  278  2.823005
13  284  0.522392

In [160]:
champion_id_to_key

      Source  Target    Weight
0         81     236  0.504851
1         81      67  0.474310
2        236      67  0.433064
3         51      81  0.378187
4        157     238  0.344551
5         81      15  0.338395
6         53     412  0.320681
7         12     412  0.314113
8        236      15  0.311336
9         51      67  0.304238
10        51     236  0.298814
11       267      16  0.293109
12        25     412  0.282001
13       117     267  0.277865
14       555     412  0.268003
15        12     201  0.265273
16        39     157  0.260559
17        51      15  0.250721
18        25      16  0.241664
19        25     267  0.241024
20       117      16  0.240323
21        15      67  0.239389
22        81     222  0.237817
23        81     412  0.234111
24        51     222  0.224639
25       201     412  0.224526
26        40      16  0.223565
27        12      25  0.222764
28        22      81  0.222487
29        12      53  0.221649
...      ...     ...       ...
7510     134      17  0.001327
7511      82      45  0.001318
7512      34      44  0.001316
7513     420     134  0.001304
7514      85      19  0.001271
7515     150      76  0.001264
7516     106     498  0.001262
7517      30     498  0.001240
7518     268      33  0.001240
7519     518      19  0.001238
7520     134      83  0.001238
7521     131      77  0.001226
7522     164      23  0.001214
7523     432      29  0.001141
7524     427     267  0.001141
7525      90      77  0.001132
7526     201      23  0.001079
7527      28      57  0.001039
7528      33     498  0.000998
7529     268      86  0.000993
7530      40      77  0.000958
7531      84      77  0.000934
7532      77     142  0.000923
7533      77     110  0.000922
7534      61      77  0.000902
7535      55     113  0.000880
7536      55      77  0.000707
7537     127      77  0.000535
7538      78      77  0.000520
7539     267      77  0.000416

[7540 rows x 3 columns]

In [163]:
x = champion_id_to_key[champion_id_to_key['Source'].isin(filtered_df['Id'])].copy()
x = x[~x['Target'].isin(filtered_df['Id'])]
#weight dikali sama tfidf nya si source then di sum untuk setiap target yg sama
x

      Source  Target    Weight
281      141     517  0.098395
373      141     203  0.087374
396      141     157  0.085235
559      141     238  0.072567
743      141     555  0.063179
823      141      56  0.059789
846      141     113  0.058946
874      141     254  0.057830
950      141      67  0.055296
1018     141     412  0.053345
1043     141      76  0.052732
1092     141      33  0.051283
1144     141      91  0.050045
1199     141       8  0.048610
1217     141      80  0.048127
1277     141     107  0.046951
1328     141     102  0.045869
1585     141     236  0.041186
1643     141      92  0.040182
1769     141     101  0.038305
1788     141      35  0.037991
1801     141      19  0.037882
1873     141     127  0.036858
1944     141      75  0.035872
1969     141       6  0.035565
2326     141      99  0.031551
2394     141      58  0.030873
2403     141       2  0.030798
2497     141     112  0.029889
2530     141     142  0.029627
...      ...     ...       ...
4743     141      78  0.016448
4770     141      17  0.016304
4841     141      14  0.015985
4861     141     498  0.015883
4865      77     106  0.015859
5000     141     497  0.015247
5012     141     106  0.015189
5327     141     133  0.013739
5531     141      44  0.012832
5533     141     143  0.012821
5682     141      27  0.012133
5729     141     117  0.011980
5762      77       6  0.011844
5795     115     142  0.011713
5920      83     238  0.011097
6092      77      67  0.010341
6106     141     267  0.010279
6202      77      26  0.009790
6449      77      45  0.008662
6515      77     101  0.008363
6631      77     112  0.007711
6685     141      37  0.007478
7025      77     238  0.005844
7053      77     143  0.005662
7066      77     157  0.005568
7166     141      82  0.004854
7251      77       8  0.004125
7460      77     498  0.001979
7532      77     142  0.000923
7533      77     110  0.000922

[94 rows x 3 columns]

In [164]:
x['Weight*Tfidf'] = x.apply(lambda row: filtered_df.loc[filtered_df['Id'] == row['Source'].item(), 'tfidf'].item() * row['Weight'], axis=1)

In [174]:
x2 = x.copy()
x2['sum_weighted_edges'] = x2.groupby(['Target'])['Weight*Tfidf'].transform(lambda x: x.sum())
x2.sort_values(by='sum_weighted_edges', ascending=False)
x3 = x2[['Target','sum_weighted_edges']]
x3 = x3.drop_duplicates(subset='Target')
x3

      Target  sum_weighted_edges
281      517            0.052387
373      203            0.046520
396      157            0.049788
559      238            0.052723
743      555            0.033638
823       56            0.031833
846      113            0.031384
874      254            0.044156
950       67            0.037626
1018     412            0.028402
1043      76            0.028076
1092      33            0.027304
1144      91            0.026645
1199       8            0.029146
1217      80            0.025624
1277     107            0.024998
1328     102            0.024422
1585     236            0.021928
1643      92            0.021394
1769     101            0.027014
1788      35            0.020227
1801      19            0.036487
1873     127            0.019624
1944      75            0.019099
1969       6            0.028310
2326      99            0.016799
2394      58            0.016437
2403       2            0.016397
2497     112            0.022017
2530     142            0.062454
...      ...                 ...
3351      25            0.012554
3355      54            0.012538
3366      61            0.012499
3395     240            0.012385
3458      15            0.012139
3541     134            0.011937
3664      89            0.011571
3721     163            0.011422
3755      98            0.011322
3885      16            0.010944
3898      18            0.010903
3970      57            0.010698
4324      48            0.009786
4384      23            0.009657
4447      85            0.009504
4691      68            0.008889
4739     110            0.009507
4743      78            0.008757
4770      17            0.008681
4841      14            0.008510
4861     498            0.010023
4865     106            0.020640
5000     497            0.008118
5327     133            0.007315
5531      44            0.006832
5682      27            0.006460
5729     117            0.006379
6106     267            0.005473
6685      37            0.003981
7166      82            0.002584

[71 rows x 2 columns]

In [175]:
###map back the key to champion id
def map_key_to_champ_id(recomm, id_key_tb):
    result = recomm
    result['Target'] = result['Target'].map(id_key_tb.set_index('Key')['Champion']) 
    return result

In [176]:
recommendation_result = map_key_to_champ_id(x3, df)
recommendation_result.sort_values(by='sum_weighted_edges', ascending=False).head(10)

       Target  sum_weighted_edges
2551     Zyra            0.099883
3198   Zilean            0.091593
2530      Zoe            0.062454
559       Zed            0.052723
281     Sylas            0.052387
396     Yasuo            0.049788
373   Kindred            0.046520
874        Vi            0.044156
950     Vayne            0.037626
1801  Warwick            0.036487